### ISSUE TITLE
Modal Popup pulling towards right on mobile device

### ISSUE THREAD

**Issue by maziz82** [maziz82/dlite#1]
![popuppullingtoright](https://cloud.githubusercontent.com/assets/26074446/25644628/f720bc78-2fea-11e7-8730-0bc3b463cc6e.jpg)

**Comment by syfer-darknight** [comment]
found the issue on mobile (form sticking too close to right)

You have this class in bootstrap

```.modal-dialog {
    position: relative;
    width: auto;
    margin: 10px;
}```

User a media query or add to existing one and change the margin (code below) for small screen size to 0px and it should fix it.

```@media only screen and (max-width : 480px) {
.modal-dialog {
    position: relative;
    width: auto;
    margin: 0px;
}
}```

Cheers

**Comment by maziz82** [comment]
Great! 

Thanks for the fix syfer. Worked like a charm.

Please clear your browser cache on mobile if you still see the issue.

Shaheem
